name: Build
on: [push]

jobs:
  linux-os:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: build appimage
      run: ./build-love-appimage.sh
    - name: Save Artefact
      uses: actions/upload-artifact@v4
      with:
        name: love-11.5-lua5.4-${{ github.sha }}.AppImage
        path: release/love-11.5-lua5.4.AppImage
  windows-os:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32]
    steps:
    - name: Clone Megasource
      uses: actions/checkout@v3
      with:
        path: megasource
        repository: alexjgriffith/megasource
        ref: 11.5-lua5.4
    - name: Checkout
      uses: actions/checkout@v3
      with:        
        path: megasource/libs/love
        repository: alexjgriffith/love
        ref: 11.5-lua5.4
    - name: Configure
      shell: cmd
      env:
        PLATFORM: ${{ matrix.platform }}
      run: cmake -Bbuild -Hmegasource -T v142 -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=%CD%\install -DLuaJIT=0 -DLUA_54=1
    - name: Install
      shell: cmd
      run: cmake --build build --config Release --target install -j2
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: love-windows-${{ matrix.platform }}
        path: install
           
